#!/bin/bash

# Setup the environment

. /usr/bin/cpwos-environment

# Copy CPW OS settings files

cp -r /etc/cpwos/dev/* $XDG_CONFIG_HOME

# Run Openbox, and have it run the autostart stuff
exec /usr/bin/openbox --startup "/usr/lib/openbox/openbox-autostart OPENBOX" "$@"
