#!/bin/bash

# Copy CPW OS settings files

case "$1" in
	dev)
		desktop_type=$1
		;;

	desktop)
		desktop_type=$1
		;;

	*)
		desktop_type="dev"
esac

cp -a /etc/cpwos/user-config/$desktop_type/. $HOME/
